Revert "Wait for any state with new adb version."
This reverts commit 8cd4f97aa1a71bac597c293fb3ce9971614a44a9.

Reason for revert: 
adb wait-for-device-recovery-rescue-sideload
error: unknown host service

Change-Id: Ibac26f091dfa1da4652cbcf7f46d7f7e926bf73e