Pathlike does not support [str] in python3.8
Fixing issue "Pathish = Union[str, os.PathLike[str]]
TypeError: 'ABCMeta' object is not subscriptable"

Change-Id: I3ee5c457ffaaf46a87e6ac7dd941525ebd7e8731